export const accounts = [
  {
    email: "murad@gmail.com",
    password: "123321",
    fullName: "Murad Aliyev",
    phoneNumber: "",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1YGbu6Fgq2vK-rEMMoOcuzzGzsh6nAs1xkg&s",
    birthdate: "",
    balance: 1000,
    accountNumber: "1111 1111 1111 1111",
    history: [],
    cvv: 123,
    expiryDate: new Date(),
  },
  {
    email: "ali@hotmail.com",
    password: "123321",
    fullName: "Ali Aliyev",
    phoneNumber: "",
    profileImage: "",
    birthdate: "",
    balance: 1000,
    accountNumber: "2222 2222 2222 2222",
    history: [],
    cvv: 123,
    expiryDate: new Date(),
  },
  {
    email: "yusif@icloud.com",
    password: "123321",
    fullName: "Yusif Elekberov",
    phoneNumber: "",
    profileImage: "",
    birthdate: "",
    balance: 1000,
    accountNumber: "3333 3333 3333 3333",
    history: [],
    cvv: 123,
    expiryDate: new Date(),
  },
  {
    email: "nadir@yahoo.com",
    password: "123321",
    fullName: "Nadir Quluzadeh",
    phoneNumber: "",
    profileImage: "",
    birthdate: "",
    balance: 1000,
    accountNumber: "4444 4444 4444 4444",
    history: [],
    cvv: 123,
    expiryDate: new Date(),
  },
];
